function(websocketpp_add_test name)
    cmake_parse_arguments(test "NO_BOOST_TEST" "" "" ${ARGN})
    websocketpp_add_executable(${name} ${test_UNPARSED_ARGUMENTS})
    if(NOT test_NO_BOOST_TEST)
        target_link_libraries(${name} PRIVATE Boost::unit_test_framework)
        if(NOT Boost_USE_STATIC_LIBS)
            target_compile_definitions(${name} PRIVATE BOOST_TEST_DYN_LINK)
        endif()
    endif()
    set_target_properties(${name} PROPERTIES FOLDER test)
    add_test(NAME ${name} COMMAND $<TARGET_FILE:${name}>)
    install(TARGETS ${name} RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
endfunction()

add_subdirectory(common)
add_subdirectory(connection)
add_subdirectory(endpoint)
add_subdirectory(extension)
add_subdirectory(http)
add_subdirectory(logger)
add_subdirectory(message_buffer)
add_subdirectory(processors)
add_subdirectory(random)
add_subdirectory(roles)
add_subdirectory(transport)
add_subdirectory(utility)
