## role unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('client.o', ["client.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('server.o', ["server.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('test_client', ["client.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_server', ["server.o"], LIBS = BOOST_LIBS)

Return('prgs')
