websocketpp_add_test(test_processor processor.cpp)
if(ZLIB_FOUND)
    websocketpp_add_test(test_processor_hybi13 hybi13.cpp)
    target_link_libraries(test_processor_hybi13 PRIVATE ZLIB::ZLIB)
    websocketpp_add_test(test_processor_extension_permessage_compress extension_permessage_compress.cpp)
    target_link_libraries(test_processor_extension_permessage_compress PRIVATE ZLIB::ZLIB)
endif()
