## processor unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs] + ['z']

objs = env.Object('test_processor.o', ["processor.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('test_hybi13.o', ["hybi13.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('test_extension_permessage_compress.o', ["extension_permessage_compress.cpp"], LIBS = BOOST_LIBS)

prgs = env.Program('test_processor', ["test_processor.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_hybi13', ["test_hybi13.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_extension_permessage_compress', ["test_extension_permessage_compress.o"], LIBS = BOOST_LIBS + ['z'])

Return('prgs')
