## utility unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('uri.o', ["uri.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('utilities.o', ["utilities.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('close.o', ["close.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('sha1.o', ["sha1.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('error.o', ["error.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('test_uri', ["uri.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_utility', ["utilities.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_frame', ["frame.cpp"], LIBS = BOOST_LIBS)
prgs += env.Program('test_close', ["close.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_sha1', ["sha1.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_error', ["error.o"], LIBS = BOOST_LIBS)

Return('prgs')
