## message_buffer unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('message.o', ["message.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('alloc.o', ["alloc.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('test_message', ["message.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_alloc', ["alloc.o"], LIBS = BOOST_LIBS)

Return('prgs')
