function(websocketpp_add_example name)
    websocketpp_add_executable(${name} ${ARGN})
    set_target_properties(${name} PROPERTIES FOLDER examples)
    install(TARGETS ${name} RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
endfunction()

add_subdirectory(associative_storage)
add_subdirectory(broadcast_server)
add_subdirectory(debug_client)
add_subdirectory(debug_server)
add_subdirectory(echo_client)
add_subdirectory(echo_server)
add_subdirectory(echo_server_both)
add_subdirectory(echo_server_tls)
add_subdirectory(enriched_storage)
add_subdirectory(external_io_service)
add_subdirectory(handler_switch)
add_subdirectory(iostream_server)
add_subdirectory(print_client)
add_subdirectory(print_client_tls)
add_subdirectory(print_server)
add_subdirectory(simple_broadcast_server)
add_subdirectory(sip_client)
add_subdirectory(subprotocol_server)
add_subdirectory(telemetry_client)
add_subdirectory(telemetry_server)
add_subdirectory(testee_client)
add_subdirectory(testee_server)
add_subdirectory(utility_client)
