## logger unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('logger_basic.o', ["basic.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('logger_basic', ["logger_basic.o"], LIBS = BOOST_LIBS)

Return('prgs')
