## Main development example
##

Import('env')
Import('boostlibs')
Import('platform_libs')

prgs = []

BOOST_LIBS = boostlibs(['unit_test_framework','system','timer','chrono'],env) + [platform_libs]
prgs += env.Program('main', ["main.cpp"], LIBS = BOOST_LIBS)

Return('prgs')
