## asio transport unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')
Import('tls_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs] + [tls_libs]

objs = env.Object('base.o', ["base.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('timers.o', ["timers.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('security.o', ["security.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('test_base', ["base.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_timers', ["timers.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_security', ["security.o"], LIBS = BOOST_LIBS)

Return('prgs')
