## random number generation unit tests
##

Import('env')
Import('boostlibs')
Import('platform_libs')

env = env.Clone ()

BOOST_LIBS = boostlibs(['unit_test_framework','system'],env) + [platform_libs]

objs = env.Object('random_none.o', ["none.cpp"], LIBS = BOOST_LIBS)
objs += env.Object('random_device.o', ["random_device.cpp"], LIBS = BOOST_LIBS)
prgs = env.Program('test_random_none', ["random_none.o"], LIBS = BOOST_LIBS)
prgs += env.Program('test_random_device', ["random_device.o"], LIBS = BOOST_LIBS)

Return('prgs')
